api_version = "2025-01"

[[extensions]]
name = "Bundle Cart Transformer"
handle = "cart-transform-extension"
type = "function"

description = "Groups bundle items together in the cart"

[[extensions.targeting]]
target = "purchase.cart-transform.run"
input_query = "src/run.graphql"
export = "run"

[extensions.build]
command = "cargo build --target wasm32-wasip1 --release"
path = "target/wasm32-wasip1/release/cart_transform_extension.wasm"
watch = [ "src/**/*.rs" ]

[extensions.ui.paths]
create = "/"
details = "/"

