# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3baf52e19aaa7d8e288d0ee5c55a3d7e"
application_url = "https://interfaces-younger-cold-menus.trycloudflare.com"
embedded = true
name = "only-bundles"
handle = "only-bundles-5"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_products,write_themes"

[auth]
redirect_urls = [
  "https://interfaces-younger-cold-menus.trycloudflare.com/auth/callback",
  "https://interfaces-younger-cold-menus.trycloudflare.com/auth/shopify/callback",
  "https://interfaces-younger-cold-menus.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
