# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "06cf693b0888af16c5d14ae91b8270ff"
application_url = "https://meet-fo-magnitude-molecules.trycloudflare.com"
embedded = true
name = "bundles"
handle = "bundles-90"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_products,write_themes"

[auth]
redirect_urls = [
  "https://meet-fo-magnitude-molecules.trycloudflare.com/auth/callback",
  "https://meet-fo-magnitude-molecules.trycloudflare.com/auth/shopify/callback",
  "https://meet-fo-magnitude-molecules.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
