# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f16d21c67ff9666d4bafc3cc08637012"
application_url = "https://example.com/"
embedded = true
name = "only-bundles"
handle = "only-bundles-3"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_products,write_themes"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false
